#server:
#  port: 9000
#spring:
#  application:
#    name: cloud-video-service
#  zipkin:
#    base-url: http://localhost:9411/ #zipkin地址
#    discovery-client-enabled: false  #不用开启服务发现
#  sleuth:
#    sampler:
#      probability: 1.0 #采样百分比
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/cloud_video?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: Sinobay2018
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#    sentinel:
#      transport:
#        dashboard: localhost:8858
#        port: 9998
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true
